# Pull nginx image
# FROM dcreg.service.consul/dev/nginx:alpine as build

# outside dcreg for aws testing purposes, should be migrated into ECR in the future
FROM nginx:alpine as build 

WORKDIR /tmp

RUN apk update \
    && apk upgrade \
    && apk add --update \
    wget \
    npm

# Get Hugo
ARG HUGO_VERSION="0.108.0"
RUN wget --quiet "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" && \
    tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz && \
    rm -r hugo_${HUGO_VERSION}_Linux-64bit.tar.gz && \
    mv hugo /usr/bin

COPY ./web_content /home/engineering-blog/web_content

COPY ./pictures /home/engineering-blog/web_content/static/pictures

WORKDIR /home/engineering-blog/web_content

RUN npm install \
    && npm i -g postcss-cli

# Create a static content
RUN hugo -D -s /home/engineering-blog/web_content -d /usr/share/nginx/html

WORKDIR /usr/share/nginx/html

# Run docker service on HTTP
EXPOSE 80

# Popy the additional nginx configuration
COPY maintanence.conf /etc/nginx/conf.d/maintanence.conf

STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
