baseURL: "https://blog.almacareer.tech/"
metaDataFormat: "yaml"
languageCode: "en-us"
title: "Engineering Blog"
theme: "blist"

timeZone: Europe/Prague

DefaultContentLanguage: "en"
DefaultContentLanguageInSubdir: true
enableEmoji: true
hidePageThumbnail: false

languages:
  en:
    contentDir: content/en
    weight: 1
    languageName: English
    params:
#      introTitle: "Engineering Blog"
#      introSubtitle: >-
#      Docs, Tips & Tricks
      introPhoto: /intro.png
      logo: /logo.png
    menu:
      main:
        - name: "Blogs"
          url: blogs/
          weight: 1
        - name: Tags
          url: tags/
          weight: 2
        - name: "Login"
          url: admin/
          weight: 3

params:
  darkModeToggle: true
  enableSearch: true
  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys:
    - tags
    - date
    - categories
    - summary
    - content
    - link
    - author

  # Table of contents
  toc: true
  copyright: "Copyright © 2022 - Developer Experience · All rights reserved"
  favicon: "/favicon.svg"
  # Color for the intro details and social links block, not applicable for dark mode - Supported values: Any color from TailwindCSS default colors. Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor: "bg-pink-50"
  # The page bundle that is shown on the front page
  frontBundle: "blogs"
  # Hide the post metadata (posted date, reading time, word count), can be used at site level or page level
  hideMeta: false
  hideOtherLanguages: true
  homepage:
    social:
      title: "Follow us,"
      description: "we provide awesome tricks and ideas!"
      icons:
        - website: instagram
          url: "https://www.instagram.com/lmc_feeling/"
        - website: facebook
          url: "https://www.facebook.com/LMC.eu/"
        - website: linkedin
          url: "https://www.linkedin.com/company/lmc/"
        - website: youtube
          url: "https://www.youtube.com/user/LMCnews"
        - website: twitter
          url: "http://bit.ly/twLMC"
        - website: github
          url: "https://github.com/almacareer"

  # Enable comments
  comments:
    system: giscus
    repo: "almacareer/blog-content"
    repoid: "R_kgDOILksLw"
    category: "Comments"
    categoryid: "DIC_kwDOILksL84CTYY4"
    mapping: "title"
    strict: "0"
    reactionsenabled: "1"
    emitmetadata: "0"
    inputposition: "bottom"
    theme: "dark_dimmed"

markup:
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

build:
  writeStats: false

googleAnalytics: ""
