name: CI
on:
  push:
    branches:
      - 'aws'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Clone related k8s repo
      uses: actions/checkout@v3
      with:
        repository: almacareer/engineering-blog--k8s
        ref: aws

    - name: Update image in Helm Chart
      run: |
        export IMAGE_VERSION="$image_name:$tag_name"
        echo "Latest version is: $IMAGE_VERSION"
        export VERSION_CHART=$(grep -oP 'appVersion: .*' engineering-blog--k8s/engineering-blog/Chart.yaml | awk '{ print $2 }')

        if [ "${IMAGE_VERSION}" == "${VERSION_CHART}" ]; then
          echo "Nothing to change."
          exit 0
        fi

        sed -i -r -e "s/appVersion: .*/appVersion: $IMAGE_VERSION/" engineering-blog--k8s/engineering-blog/Chart.yaml
        cd engineering-blog--k8s/
        git add --all
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "version: $IMAGE_VERSION"
        git push origin HEAD:aws
