---
name: Create EC2 Runner

on:
  workflow_dispatch:

jobs:
  create-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EC2 Runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          ec2-image-id: ami-0e1dc7c0757fa9cdc
          ec2-instance-type: t2.micro
          subnet-id: subnet-0114278bab913da56
          security-group-id: sg-00569d47240ff3c20
          github-token: ${{ secrets.RUNNER_GH_TOKEN }}
          label: 'Key=Name,Value=my-runner'
