---
name: Create EC2 Runner

on:
  workflow_dispatch:

jobs:
  create-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create EC2 Runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          ec2-image-id: ami-0d5d9d301c853a04a
          ec2-instance-type: t2.micro
          subnet-id: subnet-0114278bab913da56
          security-group-id: sg-00569d47240ff3c20
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'Key=Name,Value=my-runner'
